# Workflow name
name: Build

on:
  # When it will be triggered
  # And in which branch
  pull_request:
  push:
    branches:
      - master

# Where will they run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: set up JDK 1.11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11

        - name: Build debug with Gradle
          run: ./gradlew assembleDebug
